# Simple Keras Example
Please go to https://keras.io/ for the package documentation

## Load Common Package

In [1]:
import numpy as np

## Load Keras Package

In [2]:
import keras
from keras.models import Model, Sequential # We can use both of this to build a model
from keras.layers import Input, Dense, Dropout, Activation, BatchNormalization
from keras.optimizers import SGD, Adam

Using Theano backend.
Using cuDNN version 5103 on context None
Mapped name None to device cuda: Tesla K80 (0000:00:04.0)


## Basic Fully Connected Layer With Single Output
<img src="https://cdn-images-1.medium.com/max/1600/1*BMdnuQUqGEb_FSEmYIxw5g.jpeg" width="50%"/>

##### Generate Dummy Data

In [7]:
np.random.seed(0)

x_train = np.random.random((500, 3))
y_train = np.mean(x_train, axis=-1)
x_test = np.random.random((50, 3))
y_test = np.mean(x_test, axis=-1)

In [8]:
print("x_train.shape",x_train.shape)
print("y_train.shape",y_train.shape)
print("x_test.shape",x_test.shape)
print("y_test.shape",y_test.shape)
print("x_train[0]",x_train[0])
print("y_train[0]",y_train[0])
print("x_test[0]",x_test[0])
print("y_test[0]",y_test[0])

x_train.shape (500, 3)
y_train.shape (500,)
x_test.shape (50, 3)
y_test.shape (50,)
x_train[0] [ 0.5488135   0.71518937  0.60276338]
y_train[0] 0.622255415457
x_test[0] [ 0.44679332  0.83699037  0.22182403]
y_test[0] 0.501869238723


##### Initialize Model

In [9]:
sequential_model = Sequential()

In [10]:
sequential_model.add(Dense(units=4, activation='relu', input_dim=3))
sequential_model.add(Dense(units=1, input_dim=4))
sequential_model.add(Activation('tanh'))
sequential_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 16        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [11]:
sequential_model.compile(loss='mae', optimizer='adam', metrics=['mse'])

##### Train Model

In [12]:
sequential_model.fit(x_train, y_train, epochs=200, batch_size=50)

Epoch 1/200
500/500 [==============================] - 0s 82us/step - loss: 0.1679 - mean_squared_error: 0.0309
Epoch 2/200
500/500 [==============================] - 0s 19us/step - loss: 0.1305 - mean_squared_error: 0.0197
Epoch 3/200
500/500 [==============================] - 0s 19us/step - loss: 0.0918 - mean_squared_error: 0.0107
Epoch 4/200
500/500 [==============================] - 0s 18us/step - loss: 0.0593 - mean_squared_error: 0.0051
Epoch 5/200
500/500 [==============================] - 0s 19us/step - loss: 0.0490 - mean_squared_error: 0.0034
Epoch 6/200
500/500 [==============================] - 0s 18us/step - loss: 0.0472 - mean_squared_error: 0.0032
Epoch 7/200
500/500 [==============================] - 0s 18us/step - loss: 0.0443 - mean_squared_error: 0.0029
Epoch 8/200
500/500 [==============================] - 0s 18us/step - loss: 0.0415 - mean_squared_error: 0.0025
Epoch 9/200
500/500 [==============================] - 0s 18us/step - loss: 0.0388 - mean_squared_error:

500/500 [==============================] - 0s 22us/step - loss: 0.0170 - mean_squared_error: 7.1633e-04
Epoch 72/200
500/500 [==============================] - 0s 19us/step - loss: 0.0170 - mean_squared_error: 6.8657e-04
Epoch 73/200
500/500 [==============================] - 0s 19us/step - loss: 0.0170 - mean_squared_error: 7.3233e-04
Epoch 74/200
500/500 [==============================] - 0s 19us/step - loss: 0.0169 - mean_squared_error: 6.9976e-04
Epoch 75/200
500/500 [==============================] - 0s 19us/step - loss: 0.0168 - mean_squared_error: 7.2181e-04
Epoch 76/200
500/500 [==============================] - 0s 26us/step - loss: 0.0168 - mean_squared_error: 6.8601e-04
Epoch 77/200
500/500 [==============================] - 0s 20us/step - loss: 0.0169 - mean_squared_error: 7.3512e-04
Epoch 78/200
500/500 [==============================] - 0s 19us/step - loss: 0.0168 - mean_squared_error: 7.0826e-04
Epoch 79/200
500/500 [==============================] - 0s 19us/step - loss: 

500/500 [==============================] - 0s 19us/step - loss: 0.0163 - mean_squared_error: 6.7376e-04
Epoch 141/200
500/500 [==============================] - 0s 19us/step - loss: 0.0165 - mean_squared_error: 7.2338e-04
Epoch 142/200
500/500 [==============================] - 0s 20us/step - loss: 0.0164 - mean_squared_error: 6.9467e-04
Epoch 143/200
500/500 [==============================] - 0s 20us/step - loss: 0.0164 - mean_squared_error: 6.7554e-04
Epoch 144/200
500/500 [==============================] - 0s 19us/step - loss: 0.0167 - mean_squared_error: 7.2395e-04
Epoch 145/200
500/500 [==============================] - 0s 20us/step - loss: 0.0163 - mean_squared_error: 7.0034e-04
Epoch 146/200
500/500 [==============================] - 0s 21us/step - loss: 0.0163 - mean_squared_error: 7.0061e-04
Epoch 147/200
500/500 [==============================] - 0s 19us/step - loss: 0.0164 - mean_squared_error: 6.9672e-04
Epoch 148/200
500/500 [==============================] - 0s 19us/step 

##### Evaluate on Test Data

In [13]:
score = sequential_model.evaluate(x_test, y_test)
print(score)

50/50 [==============================] - 0s 50us/step
[0.022565987259149552, 0.0010462002921849489]


In [14]:
predict = sequential_model.predict(x_test)
for i in range(0, len(x_test)):
    print(x_test[i], y_test[i], predict[i])

[ 0.44679332  0.83699037  0.22182403] 0.501869238723 [ 0.50845814]
[ 0.49394526  0.92961874  0.66721471] 0.696926233965 [ 0.67199814]
[ 0.79807902  0.55099397  0.98046646] 0.776513149594 [ 0.72464728]
[ 0.58866215  0.04551071  0.1979828 ] 0.277385222861 [ 0.2633858]
[ 0.40477363  0.60127717  0.77193087] 0.592660556313 [ 0.59168291]
[ 0.41308613  0.71005831  0.7898695 ] 0.637671311343 [ 0.62823564]
[ 0.3172602   0.97927024  0.6496565 ] 0.648728977507 [ 0.63671076]
[ 0.88099806  0.55593769  0.74160311] 0.726179618916 [ 0.69163609]
[ 0.77054406  0.90824838  0.15034976] 0.609714065907 [ 0.60352826]
[ 0.55828342  0.42837851  0.92315902] 0.63660698615 [ 0.62738329]
[ 0.10509469  0.98257389  0.87545132] 0.654373302341 [ 0.64197469]
[ 0.07382628  0.49096639  0.7175595 ] 0.427450722439 [ 0.4362548]
[ 0.73815155  0.90649413  0.79986544] 0.814837035504 [ 0.74714887]
[ 0.31093038  0.49843479  0.70178576] 0.503716976381 [ 0.51190537]
[ 0.13843684  0.1939908   0.48104245] 0.271156695691 [ 0.25837383

## Let's try with Deeper Network
<img src="http://cs231n.github.io/assets/nn1/neural_net2.jpeg" width="50%"/>

##### Initialize Model

In [15]:
inputs = Input(shape=(3,))
x = Dense(units=7, activation='relu', input_dim=3)(inputs)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=1, input_dim=7)(x)
outputs = Activation('tanh')(x)

In [16]:
model = Model(inputs=inputs, outputs=outputs)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
dense_5 (Dense)              (None, 7)                 28        
_________________________________________________________________
dense_6 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_7 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_8 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_9 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 8         
__________

In [17]:
model.compile(loss='mae', optimizer='adam', metrics=['mse'])

##### Train Model

In [18]:
model.fit(x_train, y_train, epochs=200, batch_size=50)

Epoch 1/200
500/500 [==============================] - 0s 31us/step - loss: 0.4644 - mean_squared_error: 0.2468
Epoch 2/200
500/500 [==============================] - 0s 29us/step - loss: 0.4132 - mean_squared_error: 0.2007
Epoch 3/200
500/500 [==============================] - 0s 29us/step - loss: 0.3578 - mean_squared_error: 0.1575
Epoch 4/200
500/500 [==============================] - 0s 30us/step - loss: 0.2944 - mean_squared_error: 0.1150
Epoch 5/200
500/500 [==============================] - 0s 31us/step - loss: 0.2271 - mean_squared_error: 0.0761
Epoch 6/200
500/500 [==============================] - 0s 29us/step - loss: 0.1696 - mean_squared_error: 0.0455
Epoch 7/200
500/500 [==============================] - 0s 29us/step - loss: 0.1392 - mean_squared_error: 0.0291
Epoch 8/200
500/500 [==============================] - 0s 30us/step - loss: 0.1334 - mean_squared_error: 0.0256
Epoch 9/200
500/500 [==============================] - 0s 29us/step - loss: 0.1277 - mean_squared_error:

500/500 [==============================] - 0s 28us/step - loss: 0.0087 - mean_squared_error: 1.8330e-04
Epoch 72/200
500/500 [==============================] - 0s 28us/step - loss: 0.0086 - mean_squared_error: 1.7582e-04
Epoch 73/200
500/500 [==============================] - 0s 29us/step - loss: 0.0083 - mean_squared_error: 1.7525e-04
Epoch 74/200
500/500 [==============================] - 0s 32us/step - loss: 0.0083 - mean_squared_error: 1.6393e-04
Epoch 75/200
500/500 [==============================] - 0s 30us/step - loss: 0.0080 - mean_squared_error: 1.6493e-04
Epoch 76/200
500/500 [==============================] - 0s 31us/step - loss: 0.0080 - mean_squared_error: 1.6013e-04
Epoch 77/200
500/500 [==============================] - 0s 29us/step - loss: 0.0077 - mean_squared_error: 1.5449e-04
Epoch 78/200
500/500 [==============================] - 0s 29us/step - loss: 0.0074 - mean_squared_error: 1.4905e-04
Epoch 79/200
500/500 [==============================] - 0s 27us/step - loss: 

500/500 [==============================] - 0s 28us/step - loss: 0.0049 - mean_squared_error: 7.4598e-05
Epoch 141/200
500/500 [==============================] - 0s 28us/step - loss: 0.0048 - mean_squared_error: 7.4518e-05
Epoch 142/200
500/500 [==============================] - 0s 28us/step - loss: 0.0049 - mean_squared_error: 7.6032e-05
Epoch 143/200
500/500 [==============================] - 0s 27us/step - loss: 0.0046 - mean_squared_error: 7.2865e-05
Epoch 144/200
500/500 [==============================] - 0s 28us/step - loss: 0.0047 - mean_squared_error: 6.9706e-05
Epoch 145/200
500/500 [==============================] - 0s 27us/step - loss: 0.0052 - mean_squared_error: 7.7892e-05
Epoch 146/200
500/500 [==============================] - 0s 28us/step - loss: 0.0048 - mean_squared_error: 7.3698e-05
Epoch 147/200
500/500 [==============================] - 0s 28us/step - loss: 0.0049 - mean_squared_error: 7.5778e-05
Epoch 148/200
500/500 [==============================] - 0s 27us/step 

##### Evaluate on Test Data

In [19]:
score = model.evaluate(x_test, y_test)
print(score)

50/50 [==============================] - 0s 45us/step
[0.0052980100363492965, 5.6969375582411888e-05]


In [21]:
predict = model.predict(x_test)
for i in range(0, len(x_test)):
    print(x_test[i], y_test[i], predict[i])

[ 0.44679332  0.83699037  0.22182403] 0.501869238723 [ 0.50181317]
[ 0.49394526  0.92961874  0.66721471] 0.696926233965 [ 0.69802099]
[ 0.79807902  0.55099397  0.98046646] 0.776513149594 [ 0.76942849]
[ 0.58866215  0.04551071  0.1979828 ] 0.277385222861 [ 0.27360281]
[ 0.40477363  0.60127717  0.77193087] 0.592660556313 [ 0.58492184]
[ 0.41308613  0.71005831  0.7898695 ] 0.637671311343 [ 0.63338268]
[ 0.3172602   0.97927024  0.6496565 ] 0.648728977507 [ 0.64488554]
[ 0.88099806  0.55593769  0.74160311] 0.726179618916 [ 0.72569537]
[ 0.77054406  0.90824838  0.15034976] 0.609714065907 [ 0.60020947]
[ 0.55828342  0.42837851  0.92315902] 0.63660698615 [ 0.62965047]
[ 0.10509469  0.98257389  0.87545132] 0.654373302341 [ 0.64550245]
[ 0.07382628  0.49096639  0.7175595 ] 0.427450722439 [ 0.42598847]
[ 0.73815155  0.90649413  0.79986544] 0.814837035504 [ 0.80137604]
[ 0.31093038  0.49843479  0.70178576] 0.503716976381 [ 0.50355905]
[ 0.13843684  0.1939908   0.48104245] 0.271156695691 [ 0.266364

## Neural Network With Softmax Output
<img src="http://paddlepaddle.org/docs/develop/book/02.recognize_digits/image/softmax_regression_en.png" width="30%"/>

##### Generate Dummy Data

In [22]:
def generate_categorical_y(x):
    return ((x[:,0] > 0.5) * 4) + ((x[:,1] > 0.5) * 2) + (x[:,2] > 0.5)

In [23]:
np.random.seed(0)

x_train = np.random.random((1000, 3))
y_train = generate_categorical_y(x_train)
print(x_train[0], y_train[0])
print(x_train[7], y_train[7])
print(x_train[83], y_train[83])
print(x_train[83], y_train[299])

[ 0.5488135   0.71518937  0.60276338] 7
[ 0.79915856  0.46147936  0.78052918] 5
[ 0.48805628  0.35561274  0.94043195] 1
[ 0.48805628  0.35561274  0.94043195] 4


In [24]:
np.random.seed(0)

x_train = np.random.random((500, 3))
y_train = keras.utils.to_categorical(generate_categorical_y(x_train), num_classes=8)
x_test = np.random.random((50, 3))
y_test = keras.utils.to_categorical(generate_categorical_y(x_test), num_classes=8)

In [26]:
print("x_train.shape",x_train.shape)
print("y_train.shape",y_train.shape)
print("x_test.shape",x_test.shape)
print("y_test.shape",y_test.shape)
print("x_train[0]",x_train[0])
print("y_train[0]",y_train[0])
print("x_test[0]",x_train[83])
print("y_test[0]",y_train[83])

x_train.shape (500, 3)
y_train.shape (500, 8)
x_test.shape (50, 3)
y_test.shape (50, 8)
x_train[0] [ 0.5488135   0.71518937  0.60276338]
y_train[0] [ 0.  0.  0.  0.  0.  0.  0.  1.]
x_test[0] [ 0.48805628  0.35561274  0.94043195]
y_test[0] [ 0.  1.  0.  0.  0.  0.  0.  0.]


##### Initialize Model

In [27]:
inputs = Input(shape=(3,))
x = Dense(units=7, activation='relu', input_dim=3)(inputs)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=8, input_dim=7)(x)
outputs = Activation('softmax')(x)

In [28]:
model = Model(inputs=inputs, outputs=outputs)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
dense_11 (Dense)             (None, 7)                 28        
_________________________________________________________________
dense_12 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_13 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_14 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_15 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 64        
__________

In [29]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

##### Train Model

In [30]:
model.fit(x_train, y_train, epochs=500, batch_size=50)

Epoch 1/500
500/500 [==============================] - 2s 5ms/step - loss: 2.0764 - acc: 0.1360
Epoch 2/500
500/500 [==============================] - 0s 32us/step - loss: 2.0713 - acc: 0.1360
Epoch 3/500
500/500 [==============================] - 0s 32us/step - loss: 2.0643 - acc: 0.1360
Epoch 4/500
500/500 [==============================] - 0s 31us/step - loss: 2.0577 - acc: 0.1360
Epoch 5/500
500/500 [==============================] - 0s 31us/step - loss: 2.0495 - acc: 0.1360
Epoch 6/500
500/500 [==============================] - 0s 30us/step - loss: 2.0399 - acc: 0.1420
Epoch 7/500
500/500 [==============================] - 0s 31us/step - loss: 2.0297 - acc: 0.1480
Epoch 8/500
500/500 [==============================] - 0s 31us/step - loss: 2.0182 - acc: 0.1540
Epoch 9/500
500/500 [==============================] - 0s 31us/step - loss: 2.0046 - acc: 0.1580
Epoch 10/500
500/500 [==============================] - 0s 32us/step - loss: 1.9902 - acc: 0.1940
Epoch 11/500
500/500 [========

500/500 [==============================] - 0s 31us/step - loss: 0.7665 - acc: 0.6840
Epoch 85/500
500/500 [==============================] - 0s 31us/step - loss: 0.7703 - acc: 0.6960
Epoch 86/500
500/500 [==============================] - 0s 30us/step - loss: 0.7471 - acc: 0.6960
Epoch 87/500
500/500 [==============================] - 0s 31us/step - loss: 0.7478 - acc: 0.6900
Epoch 88/500
500/500 [==============================] - 0s 30us/step - loss: 0.7397 - acc: 0.7040
Epoch 89/500
500/500 [==============================] - 0s 31us/step - loss: 0.7408 - acc: 0.6900
Epoch 90/500
500/500 [==============================] - 0s 30us/step - loss: 0.7345 - acc: 0.6960
Epoch 91/500
500/500 [==============================] - 0s 31us/step - loss: 0.7357 - acc: 0.7000
Epoch 92/500
500/500 [==============================] - 0s 30us/step - loss: 0.7324 - acc: 0.6960
Epoch 93/500
500/500 [==============================] - 0s 30us/step - loss: 0.7243 - acc: 0.7020
Epoch 94/500
500/500 [===========

500/500 [==============================] - 0s 29us/step - loss: 0.6206 - acc: 0.7460
Epoch 168/500
500/500 [==============================] - 0s 29us/step - loss: 0.6147 - acc: 0.7380
Epoch 169/500
500/500 [==============================] - 0s 29us/step - loss: 0.6133 - acc: 0.7440
Epoch 170/500
500/500 [==============================] - 0s 29us/step - loss: 0.6130 - acc: 0.7420
Epoch 171/500
500/500 [==============================] - 0s 29us/step - loss: 0.6137 - acc: 0.7500
Epoch 172/500
500/500 [==============================] - 0s 29us/step - loss: 0.6154 - acc: 0.7400
Epoch 173/500
500/500 [==============================] - 0s 29us/step - loss: 0.6096 - acc: 0.7500
Epoch 174/500
500/500 [==============================] - 0s 29us/step - loss: 0.6076 - acc: 0.7500
Epoch 175/500
500/500 [==============================] - 0s 29us/step - loss: 0.6097 - acc: 0.7420
Epoch 176/500
500/500 [==============================] - 0s 29us/step - loss: 0.6036 - acc: 0.7500
Epoch 177/500
500/500 [=

500/500 [==============================] - 0s 30us/step - loss: 0.4784 - acc: 0.8060
Epoch 250/500
500/500 [==============================] - 0s 30us/step - loss: 0.4741 - acc: 0.8020
Epoch 251/500
500/500 [==============================] - 0s 30us/step - loss: 0.4720 - acc: 0.8000
Epoch 252/500
500/500 [==============================] - 0s 30us/step - loss: 0.4704 - acc: 0.8080
Epoch 253/500
500/500 [==============================] - 0s 31us/step - loss: 0.4688 - acc: 0.8020
Epoch 254/500
500/500 [==============================] - 0s 30us/step - loss: 0.4700 - acc: 0.8080
Epoch 255/500
500/500 [==============================] - 0s 31us/step - loss: 0.4660 - acc: 0.8140
Epoch 256/500
500/500 [==============================] - 0s 31us/step - loss: 0.4656 - acc: 0.8140
Epoch 257/500
500/500 [==============================] - 0s 31us/step - loss: 0.4569 - acc: 0.8140
Epoch 258/500
500/500 [==============================] - 0s 30us/step - loss: 0.4567 - acc: 0.8040
Epoch 259/500
500/500 [=

500/500 [==============================] - 0s 41us/step - loss: 0.2202 - acc: 0.9460
Epoch 332/500
500/500 [==============================] - 0s 42us/step - loss: 0.2190 - acc: 0.9400
Epoch 333/500
500/500 [==============================] - 0s 41us/step - loss: 0.2152 - acc: 0.9500
Epoch 334/500
500/500 [==============================] - 0s 33us/step - loss: 0.2198 - acc: 0.9380
Epoch 335/500
500/500 [==============================] - 0s 29us/step - loss: 0.2141 - acc: 0.9440
Epoch 336/500
500/500 [==============================] - 0s 30us/step - loss: 0.2078 - acc: 0.9500
Epoch 337/500
500/500 [==============================] - 0s 30us/step - loss: 0.2090 - acc: 0.9460
Epoch 338/500
500/500 [==============================] - 0s 29us/step - loss: 0.2048 - acc: 0.9420
Epoch 339/500
500/500 [==============================] - 0s 30us/step - loss: 0.2042 - acc: 0.9440
Epoch 340/500
500/500 [==============================] - 0s 30us/step - loss: 0.2024 - acc: 0.9460
Epoch 341/500
500/500 [=

500/500 [==============================] - 0s 31us/step - loss: 0.1208 - acc: 0.9620
Epoch 414/500
500/500 [==============================] - 0s 30us/step - loss: 0.1200 - acc: 0.9620
Epoch 415/500
500/500 [==============================] - 0s 30us/step - loss: 0.1177 - acc: 0.9680
Epoch 416/500
500/500 [==============================] - 0s 29us/step - loss: 0.1161 - acc: 0.9660
Epoch 417/500
500/500 [==============================] - 0s 30us/step - loss: 0.1163 - acc: 0.9640
Epoch 418/500
500/500 [==============================] - 0s 30us/step - loss: 0.1162 - acc: 0.9620
Epoch 419/500
500/500 [==============================] - 0s 29us/step - loss: 0.1174 - acc: 0.9640
Epoch 420/500
500/500 [==============================] - 0s 30us/step - loss: 0.1150 - acc: 0.9660
Epoch 421/500
500/500 [==============================] - 0s 30us/step - loss: 0.1151 - acc: 0.9660
Epoch 422/500
500/500 [==============================] - 0s 31us/step - loss: 0.1170 - acc: 0.9600
Epoch 423/500
500/500 [=

500/500 [==============================] - 0s 30us/step - loss: 0.0860 - acc: 0.9760
Epoch 496/500
500/500 [==============================] - 0s 31us/step - loss: 0.0866 - acc: 0.9720
Epoch 497/500
500/500 [==============================] - 0s 31us/step - loss: 0.0853 - acc: 0.9740
Epoch 498/500
500/500 [==============================] - 0s 29us/step - loss: 0.0886 - acc: 0.9700
Epoch 499/500
500/500 [==============================] - 0s 31us/step - loss: 0.0863 - acc: 0.9760
Epoch 500/500
500/500 [==============================] - 0s 31us/step - loss: 0.0863 - acc: 0.9700


##### Evaluate on Test Data

In [32]:
score = model.evaluate(x_test, y_test)
print(score)

50/50 [==============================] - 0s 60us/step
[0.17653594255447388, 0.92000000238418578]


In [33]:
predict = model.predict(x_test)
for i in range(0, len(y_test)):
    print(y_test[i], predict[i])

[ 0.  0.  1.  0.  0.  0.  0.  0.] [  3.16639537e-13   5.89223845e-17   5.87558687e-01   1.14133778e-08
   1.84989597e-06   6.69984346e-10   4.12426323e-01   1.30611852e-05]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  1.41623867e-23   7.50227258e-09   3.57094323e-05   6.98766232e-01
   4.38136502e-24   2.32065833e-09   6.54065957e-07   3.01197380e-01]
[ 0.  0.  0.  0.  0.  0.  0.  1.] [  3.30584469e-21   2.85789952e-06   1.71486807e-08   2.40963360e-04
   1.59364302e-17   4.02216949e-02   1.10846452e-06   9.59533334e-01]
[ 0.  0.  0.  0.  1.  0.  0.  0.] [  4.04064991e-02   2.41497211e-10   1.50420346e-05   1.10032171e-10
   9.59574282e-01   3.53534006e-06   6.12507733e-07   4.07805900e-10]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  4.38440813e-15   3.34385317e-03   1.96501860e-05   9.39302504e-01
   2.13103232e-17   1.62315468e-04   3.93874906e-08   5.71717024e-02]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  7.30858726e-20   1.87769692e-05   2.97045494e-06   9.68328536e-01
   1.78628199e-22   1.88187741e-

## Let's try adding Drop Out Regularization
<img src="https://cdn-images-1.medium.com/max/1600/0*dOZ6esAristenchF.png" width="30%"/>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnLKUOmbu7NS9ZxhRXNSdT27eqP8FwDnaxxCBN3vkmsfu66dWI" width="50%"/>

##### Initialize Model

In [34]:
inputs = Input(shape=(3,))
x = Dense(units=7, activation='relu', input_dim=3)(inputs)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dropout(0.1)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=7, activation='relu', input_dim=7)(x)
x = Dense(units=8, input_dim=7)(x)
outputs = Activation('softmax')(x)

In [35]:
model = Model(inputs=inputs, outputs=outputs)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
dense_17 (Dense)             (None, 7)                 28        
_________________________________________________________________
dense_18 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_19 (Dense)             (None, 7)                 56        
_________________________________________________________________
dropout_1 (Dropout)          (None, 7)                 0         
_________________________________________________________________
dense_20 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_21 (Dense)             (None, 7)                 56        
__________

In [36]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

##### Train Model

In [39]:
model.fit(x_train, y_train, epochs=500, batch_size=50)

Epoch 1/500
500/500 [==============================] - 0s 33us/step - loss: 0.1605 - acc: 0.9540
Epoch 2/500
500/500 [==============================] - 0s 32us/step - loss: 0.1334 - acc: 0.9560
Epoch 3/500
500/500 [==============================] - 0s 32us/step - loss: 0.1635 - acc: 0.9580
Epoch 4/500
500/500 [==============================] - 0s 31us/step - loss: 0.1118 - acc: 0.9780
Epoch 5/500
500/500 [==============================] - 0s 31us/step - loss: 0.1343 - acc: 0.9700
Epoch 6/500
500/500 [==============================] - 0s 32us/step - loss: 0.1229 - acc: 0.9700
Epoch 7/500
500/500 [==============================] - 0s 32us/step - loss: 0.1220 - acc: 0.9620
Epoch 8/500
500/500 [==============================] - 0s 32us/step - loss: 0.1740 - acc: 0.9400
Epoch 9/500
500/500 [==============================] - 0s 32us/step - loss: 0.1296 - acc: 0.9720
Epoch 10/500
500/500 [==============================] - 0s 32us/step - loss: 0.1384 - acc: 0.9600
Epoch 11/500
500/500 [=======

500/500 [==============================] - 0s 32us/step - loss: 0.1369 - acc: 0.9580
Epoch 85/500
500/500 [==============================] - 0s 31us/step - loss: 0.1105 - acc: 0.9680
Epoch 86/500
500/500 [==============================] - 0s 32us/step - loss: 0.0845 - acc: 0.9740
Epoch 87/500
500/500 [==============================] - 0s 31us/step - loss: 0.1157 - acc: 0.9640
Epoch 88/500
500/500 [==============================] - 0s 31us/step - loss: 0.0955 - acc: 0.9680
Epoch 89/500
500/500 [==============================] - 0s 31us/step - loss: 0.1398 - acc: 0.9600
Epoch 90/500
500/500 [==============================] - 0s 32us/step - loss: 0.0922 - acc: 0.9720
Epoch 91/500
500/500 [==============================] - 0s 32us/step - loss: 0.1576 - acc: 0.9600
Epoch 92/500
500/500 [==============================] - 0s 31us/step - loss: 0.0771 - acc: 0.9820
Epoch 93/500
500/500 [==============================] - 0s 31us/step - loss: 0.1491 - acc: 0.9640
Epoch 94/500
500/500 [===========

500/500 [==============================] - 0s 33us/step - loss: 0.1053 - acc: 0.9660
Epoch 167/500
500/500 [==============================] - 0s 33us/step - loss: 0.1138 - acc: 0.9680
Epoch 168/500
500/500 [==============================] - 0s 32us/step - loss: 0.1240 - acc: 0.9640
Epoch 169/500
500/500 [==============================] - 0s 32us/step - loss: 0.1039 - acc: 0.9740
Epoch 170/500
500/500 [==============================] - 0s 32us/step - loss: 0.0978 - acc: 0.9720
Epoch 171/500
500/500 [==============================] - 0s 32us/step - loss: 0.1068 - acc: 0.9660
Epoch 172/500
500/500 [==============================] - 0s 32us/step - loss: 0.0980 - acc: 0.9700
Epoch 173/500
500/500 [==============================] - 0s 32us/step - loss: 0.1041 - acc: 0.9720
Epoch 174/500
500/500 [==============================] - 0s 32us/step - loss: 0.1455 - acc: 0.9580
Epoch 175/500
500/500 [==============================] - 0s 32us/step - loss: 0.1031 - acc: 0.9760
Epoch 176/500
500/500 [=

500/500 [==============================] - 0s 31us/step - loss: 0.0902 - acc: 0.9720
Epoch 249/500
500/500 [==============================] - 0s 31us/step - loss: 0.1480 - acc: 0.9600
Epoch 250/500
500/500 [==============================] - 0s 32us/step - loss: 0.0910 - acc: 0.9760
Epoch 251/500
500/500 [==============================] - 0s 31us/step - loss: 0.1141 - acc: 0.9700
Epoch 252/500
500/500 [==============================] - 0s 31us/step - loss: 0.1000 - acc: 0.9700
Epoch 253/500
500/500 [==============================] - 0s 31us/step - loss: 0.0795 - acc: 0.9760
Epoch 254/500
500/500 [==============================] - 0s 32us/step - loss: 0.0965 - acc: 0.9720
Epoch 255/500
500/500 [==============================] - 0s 31us/step - loss: 0.0844 - acc: 0.9800
Epoch 256/500
500/500 [==============================] - 0s 31us/step - loss: 0.0674 - acc: 0.9860
Epoch 257/500
500/500 [==============================] - 0s 32us/step - loss: 0.1448 - acc: 0.9640
Epoch 258/500
500/500 [=

Epoch 330/500
500/500 [==============================] - 0s 31us/step - loss: 0.1502 - acc: 0.9680
Epoch 331/500
500/500 [==============================] - 0s 32us/step - loss: 0.0820 - acc: 0.9760
Epoch 332/500
500/500 [==============================] - 0s 31us/step - loss: 0.0634 - acc: 0.9840
Epoch 333/500
500/500 [==============================] - 0s 31us/step - loss: 0.1226 - acc: 0.9640
Epoch 334/500
500/500 [==============================] - 0s 31us/step - loss: 0.0951 - acc: 0.9720
Epoch 335/500
500/500 [==============================] - 0s 31us/step - loss: 0.0888 - acc: 0.9780
Epoch 336/500
500/500 [==============================] - 0s 30us/step - loss: 0.0924 - acc: 0.9800
Epoch 337/500
500/500 [==============================] - 0s 31us/step - loss: 0.0744 - acc: 0.9820
Epoch 338/500
500/500 [==============================] - 0s 32us/step - loss: 0.0910 - acc: 0.9840
Epoch 339/500
500/500 [==============================] - 0s 32us/step - loss: 0.0940 - acc: 0.9720
Epoch 340/

500/500 [==============================] - 0s 32us/step - loss: 0.1018 - acc: 0.9760
Epoch 413/500
500/500 [==============================] - 0s 31us/step - loss: 0.0910 - acc: 0.9700
Epoch 414/500
500/500 [==============================] - 0s 31us/step - loss: 0.1108 - acc: 0.9680
Epoch 415/500
500/500 [==============================] - 0s 32us/step - loss: 0.0866 - acc: 0.9820
Epoch 416/500
500/500 [==============================] - 0s 31us/step - loss: 0.1185 - acc: 0.9740
Epoch 417/500
500/500 [==============================] - 0s 32us/step - loss: 0.0817 - acc: 0.9800
Epoch 418/500
500/500 [==============================] - 0s 32us/step - loss: 0.1391 - acc: 0.9620
Epoch 419/500
500/500 [==============================] - 0s 32us/step - loss: 0.0570 - acc: 0.9860
Epoch 420/500
500/500 [==============================] - 0s 31us/step - loss: 0.1075 - acc: 0.9720
Epoch 421/500
500/500 [==============================] - 0s 32us/step - loss: 0.0845 - acc: 0.9820
Epoch 422/500
500/500 [=

500/500 [==============================] - 0s 32us/step - loss: 0.1067 - acc: 0.9760
Epoch 495/500
500/500 [==============================] - 0s 32us/step - loss: 0.0854 - acc: 0.9780
Epoch 496/500
500/500 [==============================] - 0s 32us/step - loss: 0.1190 - acc: 0.9720
Epoch 497/500
500/500 [==============================] - 0s 32us/step - loss: 0.0616 - acc: 0.9840
Epoch 498/500
500/500 [==============================] - 0s 32us/step - loss: 0.0969 - acc: 0.9760
Epoch 499/500
500/500 [==============================] - 0s 32us/step - loss: 0.0847 - acc: 0.9740
Epoch 500/500
500/500 [==============================] - 0s 33us/step - loss: 0.1385 - acc: 0.9680


##### Evaluate on Test Data

In [40]:
score = model.evaluate(x_test, y_test)
print(score)

50/50 [==============================] - 0s 46us/step
[0.16086202129721641, 0.95999999999999996]


In [41]:
predict = model.predict(x_test)
for i in range(0, len(y_test)):
    print(y_test[i], predict[i])

[ 0.  0.  1.  0.  0.  0.  0.  0.] [  2.16244895e-04   3.69710324e-06   9.92505074e-01   3.06133600e-03
   7.70366842e-06   2.09310679e-06   4.03859839e-03   1.65231046e-04]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  1.77120671e-24   1.35892230e-06   1.81293825e-26   3.24528441e-02
   1.02229258e-23   1.45717830e-04   1.21927502e-15   9.67400134e-01]
[ 0.  0.  0.  0.  0.  0.  0.  1.] [  0.00000000e+00   1.41673019e-22   0.00000000e+00   3.71781901e-24
   0.00000000e+00   2.22072913e-03   5.60519386e-45   9.97779310e-01]
[ 0.  0.  0.  0.  1.  0.  0.  0.] [  3.00269477e-07   2.20401830e-09   5.39519673e-25   9.44009220e-16
   9.91958499e-01   8.04092642e-03   1.37497042e-10   2.03390798e-07]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  5.90949696e-29   2.39174187e-04   1.43964091e-37   9.78989661e-01
   3.47491153e-31   1.06356616e-04   5.10852073e-25   2.06647571e-02]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  5.12830981e-32   2.84152666e-05   6.99062962e-40   9.81260777e-01
   2.40678083e-34   1.42919771e-

## Let's try adding Batch Normalization
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnlFLeKkzpQLzxCQSKeNYc6SVtzQIrwGDLD-v214WJQNbu0cfi" width="50%"/>
<img src="https://r2rt.com/static/images/BN_output_23_0.png" width="50%"/>

##### Initialize Model

In [42]:
inputs = Input(shape=(3,))
x = Dense(units=7, input_dim=3)(inputs)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dense(units=7, input_dim=7)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dense(units=7, input_dim=7)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dropout(0.1)(x)
x = Dense(units=7, input_dim=7)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dense(units=7, input_dim=7)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dense(units=8, input_dim=7)(x)
x = BatchNormalization()(x)
outputs = Activation('softmax')(x)

In [43]:
model = Model(inputs=inputs, outputs=outputs)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
dense_23 (Dense)             (None, 7)                 28        
_________________________________________________________________
batch_normalization_1 (Batch (None, 7)                 28        
_________________________________________________________________
activation_6 (Activation)    (None, 7)                 0         
_________________________________________________________________
dense_24 (Dense)             (None, 7)                 56        
_________________________________________________________________
batch_normalization_2 (Batch (None, 7)                 28        
_________________________________________________________________
activation_7 (Activation)    (None, 7)                 0         
__________

In [44]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

##### Train Model

In [45]:
model.fit(x_train, y_train, epochs=500, batch_size=50)

Epoch 1/500
500/500 [==============================] - 0s 90us/step - loss: 2.6482 - acc: 0.0800
Epoch 2/500
500/500 [==============================] - 0s 88us/step - loss: 2.4038 - acc: 0.1120
Epoch 3/500
500/500 [==============================] - 0s 87us/step - loss: 2.2000 - acc: 0.1800
Epoch 4/500
500/500 [==============================] - 0s 88us/step - loss: 2.0433 - acc: 0.2220
Epoch 5/500
500/500 [==============================] - 0s 87us/step - loss: 1.9181 - acc: 0.2560
Epoch 6/500
500/500 [==============================] - 0s 88us/step - loss: 1.8329 - acc: 0.2860
Epoch 7/500
500/500 [==============================] - 0s 90us/step - loss: 1.7687 - acc: 0.3420
Epoch 8/500
500/500 [==============================] - 0s 78us/step - loss: 1.6699 - acc: 0.3820
Epoch 9/500
500/500 [==============================] - 0s 78us/step - loss: 1.6540 - acc: 0.4040
Epoch 10/500
500/500 [==============================] - 0s 77us/step - loss: 1.5394 - acc: 0.4720
Epoch 11/500
500/500 [=======

500/500 [==============================] - 0s 73us/step - loss: 0.8144 - acc: 0.7420
Epoch 85/500
500/500 [==============================] - 0s 74us/step - loss: 0.8310 - acc: 0.7400
Epoch 86/500
500/500 [==============================] - 0s 77us/step - loss: 0.8028 - acc: 0.7360
Epoch 87/500
500/500 [==============================] - 0s 72us/step - loss: 0.8082 - acc: 0.7420
Epoch 88/500
500/500 [==============================] - 0s 72us/step - loss: 0.7762 - acc: 0.7660
Epoch 89/500
500/500 [==============================] - 0s 72us/step - loss: 0.8224 - acc: 0.7420
Epoch 90/500
500/500 [==============================] - 0s 72us/step - loss: 0.8472 - acc: 0.7200
Epoch 91/500
500/500 [==============================] - 0s 74us/step - loss: 0.7156 - acc: 0.7720
Epoch 92/500
500/500 [==============================] - 0s 73us/step - loss: 0.7852 - acc: 0.7600
Epoch 93/500
500/500 [==============================] - 0s 73us/step - loss: 0.6811 - acc: 0.8060
Epoch 94/500
500/500 [===========

500/500 [==============================] - 0s 73us/step - loss: 0.5013 - acc: 0.8540
Epoch 168/500
500/500 [==============================] - 0s 72us/step - loss: 0.5530 - acc: 0.8080
Epoch 169/500
500/500 [==============================] - 0s 72us/step - loss: 0.5254 - acc: 0.8420
Epoch 170/500
500/500 [==============================] - 0s 73us/step - loss: 0.5483 - acc: 0.8140
Epoch 171/500
500/500 [==============================] - 0s 75us/step - loss: 0.5395 - acc: 0.8400
Epoch 172/500
500/500 [==============================] - 0s 75us/step - loss: 0.4450 - acc: 0.8760
Epoch 173/500
500/500 [==============================] - 0s 74us/step - loss: 0.5302 - acc: 0.8320
Epoch 174/500
500/500 [==============================] - 0s 74us/step - loss: 0.5691 - acc: 0.8120
Epoch 175/500
500/500 [==============================] - 0s 74us/step - loss: 0.5949 - acc: 0.8140
Epoch 176/500
500/500 [==============================] - 0s 73us/step - loss: 0.5879 - acc: 0.7980
Epoch 177/500
500/500 [=

500/500 [==============================] - 0s 74us/step - loss: 0.4790 - acc: 0.8420
Epoch 250/500
500/500 [==============================] - 0s 76us/step - loss: 0.5362 - acc: 0.8320
Epoch 251/500
500/500 [==============================] - 0s 73us/step - loss: 0.4884 - acc: 0.8400
Epoch 252/500
500/500 [==============================] - 0s 74us/step - loss: 0.4465 - acc: 0.8480
Epoch 253/500
500/500 [==============================] - 0s 77us/step - loss: 0.5214 - acc: 0.8300
Epoch 254/500
500/500 [==============================] - 0s 73us/step - loss: 0.4161 - acc: 0.8820
Epoch 255/500
500/500 [==============================] - 0s 74us/step - loss: 0.4480 - acc: 0.8580
Epoch 256/500
500/500 [==============================] - 0s 75us/step - loss: 0.4402 - acc: 0.8660
Epoch 257/500
500/500 [==============================] - 0s 74us/step - loss: 0.4835 - acc: 0.8360
Epoch 258/500
500/500 [==============================] - 0s 73us/step - loss: 0.5406 - acc: 0.8320
Epoch 259/500
500/500 [=

500/500 [==============================] - 0s 89us/step - loss: 0.4491 - acc: 0.8500
Epoch 332/500
500/500 [==============================] - 0s 74us/step - loss: 0.4250 - acc: 0.8560
Epoch 333/500
500/500 [==============================] - 0s 74us/step - loss: 0.4216 - acc: 0.8520
Epoch 334/500
500/500 [==============================] - 0s 72us/step - loss: 0.4321 - acc: 0.8460
Epoch 335/500
500/500 [==============================] - 0s 71us/step - loss: 0.4956 - acc: 0.8280
Epoch 336/500
500/500 [==============================] - 0s 72us/step - loss: 0.4277 - acc: 0.8460
Epoch 337/500
500/500 [==============================] - 0s 73us/step - loss: 0.4832 - acc: 0.8520
Epoch 338/500
500/500 [==============================] - 0s 72us/step - loss: 0.4895 - acc: 0.8560
Epoch 339/500
500/500 [==============================] - 0s 72us/step - loss: 0.4216 - acc: 0.8720
Epoch 340/500
500/500 [==============================] - 0s 72us/step - loss: 0.3940 - acc: 0.8700
Epoch 341/500
500/500 [=

500/500 [==============================] - 0s 73us/step - loss: 0.3570 - acc: 0.8700
Epoch 414/500
500/500 [==============================] - 0s 72us/step - loss: 0.3923 - acc: 0.8680
Epoch 415/500
500/500 [==============================] - 0s 72us/step - loss: 0.4316 - acc: 0.8600
Epoch 416/500
500/500 [==============================] - 0s 72us/step - loss: 0.3777 - acc: 0.8800
Epoch 417/500
500/500 [==============================] - 0s 72us/step - loss: 0.4081 - acc: 0.8520
Epoch 418/500
500/500 [==============================] - 0s 72us/step - loss: 0.5008 - acc: 0.8280
Epoch 419/500
500/500 [==============================] - 0s 73us/step - loss: 0.3691 - acc: 0.8840
Epoch 420/500
500/500 [==============================] - 0s 76us/step - loss: 0.4190 - acc: 0.8780
Epoch 421/500
500/500 [==============================] - 0s 75us/step - loss: 0.4454 - acc: 0.8600
Epoch 422/500
500/500 [==============================] - 0s 75us/step - loss: 0.3761 - acc: 0.8840
Epoch 423/500
500/500 [=

500/500 [==============================] - 0s 72us/step - loss: 0.4121 - acc: 0.8760
Epoch 496/500
500/500 [==============================] - 0s 71us/step - loss: 0.3323 - acc: 0.8940
Epoch 497/500
500/500 [==============================] - 0s 72us/step - loss: 0.4778 - acc: 0.8260
Epoch 498/500
500/500 [==============================] - 0s 72us/step - loss: 0.3446 - acc: 0.8980
Epoch 499/500
500/500 [==============================] - 0s 72us/step - loss: 0.3614 - acc: 0.8760
Epoch 500/500
500/500 [==============================] - 0s 74us/step - loss: 0.3506 - acc: 0.8780


##### Evaluate on Test Data

In [46]:
score = model.evaluate(x_test, y_test)
print(score)

50/50 [==============================] - 0s 75us/step
[0.15342027783393861, 0.97999999999999998]


In [47]:
predict = model.predict(x_test)
for i in range(0, len(y_test)):
    print(y_test[i], predict[i])

[ 0.  0.  1.  0.  0.  0.  0.  0.] [  1.36111677e-02   6.38939848e-04   8.48335624e-01   5.18873194e-03
   1.70630123e-02   8.30739213e-04   1.14125989e-01   2.05756529e-04]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [ 0.00573244  0.00223672  0.04949012  0.19709764  0.00415999  0.01036232
  0.04730948  0.68361133]
[ 0.  0.  0.  0.  0.  0.  0.  1.] [ 0.0025018   0.03300815  0.01374928  0.03724385  0.01176558  0.43173605
  0.02335984  0.4466354 ]
[ 0.  0.  0.  0.  1.  0.  0.  0.] [ 0.05017398  0.00716297  0.0134681   0.00337593  0.78126734  0.11121393
  0.02994093  0.00339675]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [ 0.00239856  0.01737203  0.02123119  0.94177747  0.0069781   0.00305533
  0.00134271  0.00584457]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  1.54645147e-03   6.93713827e-03   1.39147062e-02   9.54786360e-01
   2.93386821e-03   2.68539158e-03   6.56034506e-04   1.65400375e-02]
[ 0.  0.  0.  1.  0.  0.  0.  0.] [  4.05569182e-04   6.48239907e-03   3.68809775e-02   9.43811178e-01
   6.06185524e-03  